import Head from "next/head";
import Link from "next/link";
import React from "react";
// import { logo } from "../public";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>DALL-E Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full flex justify-between items-center bg-white sm:px-8 px-4 py-4 border-b border-b-[#e6ebf4]">
        <Link href="/">
          <img src="/logo.svg" alt="logo" className="w-28 object-contain" />
        </Link>
        <Link
          href="/createPost"
          className="font-inter font-medium bg-[#6469ff] text-white px-4 py-2 rounded-md"
        >
          Create
        </Link>
      </header>
      <main className="sm:p-8 p-4 py-8 w-full bg-[#f9fafe] min-h-[calc(100vh-73px)]">
        {children}
      </main>
    </>
  );
};

export default Layout;
